return 0;

namespace Scripts
{
    internal static class FetchUrlScratchConfigV7
    {
        public const string BaseUrl = "https://cruzlauroiii.github.io";
        public static readonly (string Label, string Path, string Mode, string Pattern, string Method, int Follow)[] Probes =
        [
            ("chat-004", "/wolfstruckingco.com/Chat/004/", "head", "", "HEAD", 1),
            ("chat-005", "/wolfstruckingco.com/Chat/005/", "head", "", "HEAD", 1),
            ("chat-006", "/wolfstruckingco.com/Chat/006/", "head", "", "HEAD", 1),
            ("chat-007", "/wolfstruckingco.com/Chat/007/", "head", "", "HEAD", 1),
            ("chat-008", "/wolfstruckingco.com/Chat/008/", "head", "", "HEAD", 1),
            ("chat-009", "/wolfstruckingco.com/Chat/009/", "head", "", "HEAD", 1),
            ("chat-013", "/wolfstruckingco.com/Chat/013/", "head", "", "HEAD", 1),
            ("chat-014", "/wolfstruckingco.com/Chat/014/", "head", "", "HEAD", 1),
            ("chat-015", "/wolfstruckingco.com/Chat/015/", "head", "", "HEAD", 1),
            ("chat-020", "/wolfstruckingco.com/Chat/020/", "head", "", "HEAD", 1),
            ("chat-021", "/wolfstruckingco.com/Chat/021/", "head", "", "HEAD", 1),
            ("chat-022", "/wolfstruckingco.com/Chat/022/", "head", "", "HEAD", 1),
            ("chat-027", "/wolfstruckingco.com/Chat/027/", "head", "", "HEAD", 1),
            ("chat-028", "/wolfstruckingco.com/Chat/028/", "head", "", "HEAD", 1),
            ("chat-029", "/wolfstruckingco.com/Chat/029/", "head", "", "HEAD", 1),
            ("chat-034", "/wolfstruckingco.com/Chat/034/", "head", "", "HEAD", 1),
            ("chat-035", "/wolfstruckingco.com/Chat/035/", "head", "", "HEAD", 1),
            ("chat-036", "/wolfstruckingco.com/Chat/036/", "head", "", "HEAD", 1),
            ("chat-065", "/wolfstruckingco.com/Chat/065/", "head", "", "HEAD", 1),
            ("chat-066", "/wolfstruckingco.com/Chat/066/", "head", "", "HEAD", 1),
            ("chat-067", "/wolfstruckingco.com/Chat/067/", "head", "", "HEAD", 1),
            ("chat-071", "/wolfstruckingco.com/Chat/071/", "head", "", "HEAD", 1),
            ("chat-076", "/wolfstruckingco.com/Chat/076/", "head", "", "HEAD", 1),
            ("chat-081", "/wolfstruckingco.com/Chat/081/", "head", "", "HEAD", 1),
            ("chat-085", "/wolfstruckingco.com/Chat/085/", "head", "", "HEAD", 1),
            ("chat-087", "/wolfstruckingco.com/Chat/087/", "head", "", "HEAD", 1),
            ("chat-088", "/wolfstruckingco.com/Chat/088/", "head", "", "HEAD", 1),
            ("chat-094", "/wolfstruckingco.com/Chat/094/", "head", "", "HEAD", 1),
            ("chat-095", "/wolfstruckingco.com/Chat/095/", "head", "", "HEAD", 1),
            ("chat-101", "/wolfstruckingco.com/Chat/101/", "head", "", "HEAD", 1),
            ("chat-102", "/wolfstruckingco.com/Chat/102/", "head", "", "HEAD", 1),
            ("chat-103", "/wolfstruckingco.com/Chat/103/", "head", "", "HEAD", 1),
            ("chat-104", "/wolfstruckingco.com/Chat/104/", "head", "", "HEAD", 1),
            ("chat-105", "/wolfstruckingco.com/Chat/105/", "head", "", "HEAD", 1),
            ("chat-106", "/wolfstruckingco.com/Chat/106/", "head", "", "HEAD", 1),
            ("apply-012", "/wolfstruckingco.com/Apply/012/", "head", "", "HEAD", 1),
            ("apply-017", "/wolfstruckingco.com/Apply/017/", "head", "", "HEAD", 1),
            ("apply-019", "/wolfstruckingco.com/Apply/019/", "head", "", "HEAD", 1),
            ("apply-024", "/wolfstruckingco.com/Apply/024/", "head", "", "HEAD", 1),
            ("apply-026", "/wolfstruckingco.com/Apply/026/", "head", "", "HEAD", 1),
            ("apply-031", "/wolfstruckingco.com/Apply/031/", "head", "", "HEAD", 1),
            ("apply-033", "/wolfstruckingco.com/Apply/033/", "head", "", "HEAD", 1),
            ("apply-038", "/wolfstruckingco.com/Apply/038/", "head", "", "HEAD", 1),
            ("apply-044", "/wolfstruckingco.com/Apply/044/", "head", "", "HEAD", 1),
            ("apply-046", "/wolfstruckingco.com/Apply/046/", "head", "", "HEAD", 1),
            ("apply-048", "/wolfstruckingco.com/Apply/048/", "head", "", "HEAD", 1),
            ("apply-050", "/wolfstruckingco.com/Apply/050/", "head", "", "HEAD", 1),
            ("documents-016", "/wolfstruckingco.com/Documents/016/", "head", "", "HEAD", 1),
            ("documents-023", "/wolfstruckingco.com/Documents/023/", "head", "", "HEAD", 1),
            ("documents-030", "/wolfstruckingco.com/Documents/030/", "head", "", "HEAD", 1),
            ("documents-037", "/wolfstruckingco.com/Documents/037/", "head", "", "HEAD", 1),
            ("dashboard-045", "/wolfstruckingco.com/Dashboard/045/", "head", "", "HEAD", 1),
            ("dashboard-047", "/wolfstruckingco.com/Dashboard/047/", "head", "", "HEAD", 1),
            ("dashboard-049", "/wolfstruckingco.com/Dashboard/049/", "head", "", "HEAD", 1),
            ("dashboard-051", "/wolfstruckingco.com/Dashboard/051/", "head", "", "HEAD", 1),
            ("map-060", "/wolfstruckingco.com/Map/060/", "head", "", "HEAD", 1),
            ("map-061", "/wolfstruckingco.com/Map/061/", "head", "", "HEAD", 1),
            ("map-062", "/wolfstruckingco.com/Map/062/", "head", "", "HEAD", 1),
            ("map-063", "/wolfstruckingco.com/Map/063/", "head", "", "HEAD", 1),
            ("map-064", "/wolfstruckingco.com/Map/064/", "head", "", "HEAD", 1),
            ("map-068", "/wolfstruckingco.com/Map/068/", "head", "", "HEAD", 1),
            ("map-069", "/wolfstruckingco.com/Map/069/", "head", "", "HEAD", 1),
            ("map-070", "/wolfstruckingco.com/Map/070/", "head", "", "HEAD", 1),
            ("map-077", "/wolfstruckingco.com/Map/077/", "head", "", "HEAD", 1),
            ("map-078", "/wolfstruckingco.com/Map/078/", "head", "", "HEAD", 1),
            ("map-079", "/wolfstruckingco.com/Map/079/", "head", "", "HEAD", 1),
            ("map-080", "/wolfstruckingco.com/Map/080/", "head", "", "HEAD", 1),
            ("map-082", "/wolfstruckingco.com/Map/082/", "head", "", "HEAD", 1),
            ("map-086", "/wolfstruckingco.com/Map/086/", "head", "", "HEAD", 1),
            ("map-089", "/wolfstruckingco.com/Map/089/", "head", "", "HEAD", 1),
            ("map-090", "/wolfstruckingco.com/Map/090/", "head", "", "HEAD", 1),
            ("map-091", "/wolfstruckingco.com/Map/091/", "head", "", "HEAD", 1),
            ("map-092", "/wolfstruckingco.com/Map/092/", "head", "", "HEAD", 1),
            ("map-093", "/wolfstruckingco.com/Map/093/", "head", "", "HEAD", 1),
            ("map-096", "/wolfstruckingco.com/Map/096/", "head", "", "HEAD", 1),
            ("map-097", "/wolfstruckingco.com/Map/097/", "head", "", "HEAD", 1),
            ("map-098", "/wolfstruckingco.com/Map/098/", "head", "", "HEAD", 1),
            ("map-099", "/wolfstruckingco.com/Map/099/", "head", "", "HEAD", 1),
            ("map-100", "/wolfstruckingco.com/Map/100/", "head", "", "HEAD", 1),
            ("track-072", "/wolfstruckingco.com/Track/072/", "head", "", "HEAD", 1),
            ("track-073", "/wolfstruckingco.com/Track/073/", "head", "", "HEAD", 1),
            ("track-074", "/wolfstruckingco.com/Track/074/", "head", "", "HEAD", 1),
            ("track-075", "/wolfstruckingco.com/Track/075/", "head", "", "HEAD", 1),
            ("track-083", "/wolfstruckingco.com/Track/083/", "head", "", "HEAD", 1),
            ("track-121", "/wolfstruckingco.com/Track/121/", "head", "", "HEAD", 1),
            ("admin-040", "/wolfstruckingco.com/Admin/040/", "head", "", "HEAD", 1),
            ("hiringhall-041", "/wolfstruckingco.com/HiringHall/041/", "head", "", "HEAD", 1),
            ("hiringhall-042", "/wolfstruckingco.com/HiringHall/042/", "head", "", "HEAD", 1),
            ("hiringhall-043", "/wolfstruckingco.com/HiringHall/043/", "head", "", "HEAD", 1),
            ("marketplace-010", "/wolfstruckingco.com/Marketplace/010/", "head", "", "HEAD", 1),
            ("marketplace-054", "/wolfstruckingco.com/Marketplace/054/", "head", "", "HEAD", 1),
            ("marketplace-120", "/wolfstruckingco.com/Marketplace/120/", "head", "", "HEAD", 1),
            ("schedule-084", "/wolfstruckingco.com/Schedule/084/", "head", "", "HEAD", 1),
            ("kpi-107", "/wolfstruckingco.com/Investors/KPI/107/", "head", "", "HEAD", 1),
            ("kpi-108", "/wolfstruckingco.com/Investors/KPI/108/", "head", "", "HEAD", 1),
            ("kpi-109", "/wolfstruckingco.com/Investors/KPI/109/", "head", "", "HEAD", 1),
            ("kpi-110", "/wolfstruckingco.com/Investors/KPI/110/", "head", "", "HEAD", 1),
            ("kpi-111", "/wolfstruckingco.com/Investors/KPI/111/", "head", "", "HEAD", 1),
            ("kpi-112", "/wolfstruckingco.com/Investors/KPI/112/", "head", "", "HEAD", 1),
            ("kpi-113", "/wolfstruckingco.com/Investors/KPI/113/", "head", "", "HEAD", 1),
            ("kpi-114", "/wolfstruckingco.com/Investors/KPI/114/", "head", "", "HEAD", 1),
            ("kpi-115", "/wolfstruckingco.com/Investors/KPI/115/", "head", "", "HEAD", 1),
            ("kpi-116", "/wolfstruckingco.com/Investors/KPI/116/", "head", "", "HEAD", 1),
            ("kpi-117", "/wolfstruckingco.com/Investors/KPI/117/", "head", "", "HEAD", 1),
            ("kpi-118", "/wolfstruckingco.com/Investors/KPI/118/", "head", "", "HEAD", 1),
            ("kpi-119", "/wolfstruckingco.com/Investors/KPI/119/", "head", "", "HEAD", 1),
        ];
    }
}
