return 0;

namespace Scripts
{
    internal static class PatchSourceScratchConfigV166
    {
        public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\src\SharedUI\Pages\ChatPage.razor.cs";

        public const string Find_01 = "using System;\nusing System.Threading.Tasks;\nusing Domain.Constants;\nusing Microsoft.AspNetCore.Components;\nusing SharedUI.Services;\n\nnamespace SharedUI.Pages;\n\npublic partial class ChatPage : ComponentBase\n{\n    private static readonly ChatVariant SellerVariant = new(\n        ChatVariantConstants.SellSystemPrompt,\n        ChatVariantConstants.SellerLede,\n        ChatVariantConstants.SellerPlaceholder,\n        ChatVariantConstants.SellerCallTitle,\n        ChatVariantConstants.SellerAttachTitle,\n        ChatVariantConstants.SellerSubject);\n\n    private static readonly ChatVariant DriverVariant = new(\n        ChatVariantConstants.ApplicantSystemPrompt,\n        ChatVariantConstants.DriverLede,\n        ChatVariantConstants.DriverPlaceholder,\n        ChatVariantConstants.DriverCallTitle,\n        ChatVariantConstants.DriverAttachTitle,\n        ChatVariantConstants.DriverSubject);\n\n    private static readonly ChatVariant DispatcherChatVariant = new(\n        ChatVariantConstants.DispatcherSystemPrompt,\n        ChatVariantConstants.DispatcherLede,\n        ChatVariantConstants.DispatcherPlaceholder,\n        ChatVariantConstants.DispatcherCallTitle,\n        ChatVariantConstants.DispatcherAttachTitle,\n        ChatVariantConstants.DispatcherSubject);\n\n    [Inject]\n    private WolfsInteropService Wolfs { get; set; } = null!;\n\n    private bool ShowSignInPrompt { get; set; }\n\n    private ChatVariant CurrentVariant { get; set; } = SellerVariant;\n\n    protected override async Task OnAfterRenderAsync(bool firstRender)\n    {\n        if (!firstRender) { return; }\n        var Auth = await Wolfs.AuthGetAsync();\n        var Role = Auth?.Role ?? string.Empty;\n        if (string.IsNullOrEmpty(Role))\n        {\n            ShowSignInPrompt = true;\n            StateHasChanged();\n            return;\n        }\n        var Resolved = ResolveVariantByRole(Role);\n        if (!ReferenceEquals(Resolved, CurrentVariant))\n        {\n            CurrentVariant = Resolved;\n            StateHasChanged();\n        }\n    }\n\n    private static ChatVariant ResolveVariantByRole(string Role)\n    {\n        return Role switch\n        {\n            ChatVariantConstants.ApplicantRole => DriverVariant,\n            ChatVariantConstants.DispatcherRole => DispatcherChatVariant,\n            var R when R.StartsWith(ChatVariantConstants.DriverRolePrefix, StringComparison.Ordinal) => DriverVariant,\n            _ => SellerVariant,\n        };\n    }\n\n    private sealed record ChatVariant(string SystemPrompt, string Lede, string Placeholder, string CallTitle, string AttachTitle, string Subject);\n}\n";
        public const string Replace_01 = "using System;\nusing Domain.Constants;\n\nnamespace SharedUI.Pages;\n\npublic partial class ChatPage\n{\n    private static readonly ChatVariant SellerVariant = new(\n        ChatVariantConstants.SellSystemPrompt,\n        ChatVariantConstants.SellerLede,\n        ChatVariantConstants.SellerPlaceholder,\n        ChatVariantConstants.SellerCallTitle,\n        ChatVariantConstants.SellerAttachTitle,\n        ChatVariantConstants.SellerSubject);\n\n    private static readonly ChatVariant DriverVariant = new(\n        ChatVariantConstants.ApplicantSystemPrompt,\n        ChatVariantConstants.DriverLede,\n        ChatVariantConstants.DriverPlaceholder,\n        ChatVariantConstants.DriverCallTitle,\n        ChatVariantConstants.DriverAttachTitle,\n        ChatVariantConstants.DriverSubject);\n\n    private static readonly ChatVariant DispatcherChatVariant = new(\n        ChatVariantConstants.DispatcherSystemPrompt,\n        ChatVariantConstants.DispatcherLede,\n        ChatVariantConstants.DispatcherPlaceholder,\n        ChatVariantConstants.DispatcherCallTitle,\n        ChatVariantConstants.DispatcherAttachTitle,\n        ChatVariantConstants.DispatcherSubject);\n\n    private bool ShowSignInPrompt { get; set; }\n\n    private ChatVariant CurrentVariant { get; set; } = SellerVariant;\n\n    private static ChatVariant ResolveVariantByRole(string Role)\n    {\n        return Role switch\n        {\n            ChatVariantConstants.ApplicantRole => DriverVariant,\n            ChatVariantConstants.DispatcherRole => DispatcherChatVariant,\n            var R when R.StartsWith(ChatVariantConstants.DriverRolePrefix, StringComparison.Ordinal) => DriverVariant,\n            _ => SellerVariant,\n        };\n    }\n\n    private sealed record ChatVariant(string SystemPrompt, string Lede, string Placeholder, string CallTitle, string AttachTitle, string Subject);\n}\n";

        public const string Find_02 = "___UNUSED_SLOT___";
        public const string Replace_02 = "";
    }
}
