return 0;

namespace Scripts
{
    internal static class PatchSourcePipelineCdpRefactorConfig
    {
        public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\docs\videos\run-crud-pipeline.cs";

        public const string Find_01 = "// Chrome CDP setup. Discover the port from DevToolsActivePort (same as chrome-devtools.cs)\n// because Chrome 144+ approval-mode binds an arbitrary port, not the legacy 9222.\nusing var Http = new HttpClient { Timeout = TimeSpan.FromSeconds(10) };\nvar ChromeUserDataDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), \"Google\", \"Chrome\", \"User Data\");\nvar ActivePortFile = Path.Combine(ChromeUserDataDir, \"DevToolsActivePort\");\nint CdpPort = 9222;\nif (File.Exists(ActivePortFile))\n{\n    var ActiveLines = await File.ReadAllLinesAsync(ActivePortFile);\n    if (ActiveLines.Length >= 1 && int.TryParse(ActiveLines[0].Trim(), out var DiscoveredPort)) { CdpPort = DiscoveredPort; }\n}\nvar TargetsJson = JsonDocument.Parse(await Http.GetStringAsync($\"http://127.0.0.1:{CdpPort.ToString(System.Globalization.CultureInfo.InvariantCulture)}/json/list\"));\nJsonElement PageT = default;\nforeach (var T in TargetsJson.RootElement.EnumerateArray())\n{\n    if (T.GetProperty(\"type\").GetString() == \"page\") { PageT = T; break; }\n}\nvar WsUrl = PageT.GetProperty(\"webSocketDebuggerUrl\").GetString()!;\nusing var Ws = new ClientWebSocket();\nawait Ws.ConnectAsync(new Uri(WsUrl), default);\n\nint CmdId = 1;\nasync Task<JsonNode> Send(string Method, object? Params = null)\n{\n    var Id = CmdId++;\n    var Msg = new JsonObject { [\"id\"] = Id, [\"method\"] = Method };\n    if (Params != null) { Msg[\"params\"] = JsonNode.Parse(JsonSerializer.Serialize(Params)); }\n    var Bytes = Encoding.UTF8.GetBytes(Msg.ToJsonString());\n    await Ws.SendAsync(Bytes, WebSocketMessageType.Text, true, default);";

        public const string Replace_01 = "// Chrome CDP setup via DevToolsActivePort + browser WS + Target.attachToTarget(flatten:true).\n// Refs: https://chromedevtools.github.io/devtools-protocol/tot/Target/ (flatten flag),\n// https://github.com/aslushnikov/getting-started-with-cdp (attachToTarget pattern).\nvar ChromeUserDataDir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), \"Google\", \"Chrome\", \"User Data\");\nvar ActivePortFile = Path.Combine(ChromeUserDataDir, \"DevToolsActivePort\");\nif (!File.Exists(ActivePortFile)) { throw new InvalidOperationException(\"DevToolsActivePort not found - is Chrome running with remote debugging?\"); }\nvar PortLines = await File.ReadAllLinesAsync(ActivePortFile);\nvar CdpPort = int.Parse(PortLines[0].Trim(), System.Globalization.CultureInfo.InvariantCulture);\nvar BrowserPath = PortLines.Length >= 2 ? PortLines[1].Trim() : \"/devtools/browser\";\nvar BrowserWsUrl = $\"ws://127.0.0.1:{CdpPort.ToString(System.Globalization.CultureInfo.InvariantCulture)}{BrowserPath}\";\nusing var Ws = new ClientWebSocket();\nawait Ws.ConnectAsync(new Uri(BrowserWsUrl), default);\n\nint CmdId = 1;\nstring? AttachedSessionId = null;\nasync Task<JsonNode> Send(string Method, object? Params = null)\n{\n    var Id = CmdId++;\n    var Msg = new JsonObject { [\"id\"] = Id, [\"method\"] = Method };\n    if (Params != null) { Msg[\"params\"] = JsonNode.Parse(JsonSerializer.Serialize(Params)); }\n    if (AttachedSessionId != null && Method != \"Target.getTargets\" && Method != \"Target.attachToTarget\") { Msg[\"sessionId\"] = AttachedSessionId; }\n    var Bytes = Encoding.UTF8.GetBytes(Msg.ToJsonString());\n    await Ws.SendAsync(Bytes, WebSocketMessageType.Text, true, default);";
    }
}
