return 0;

namespace Scripts
{
    internal static class PatchSourceScratchConfigV83
    {
        public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\docs\videos\run-crud-pipeline.cs";

        public const string Find_01 = "    await Cdp.DismissInfobarAsync();\n    var ChatScrollExpr = \"(function(){try{if(location.pathname.indexOf('/Chat')>-1){var s=document.querySelector('.ChatStream');if(s&&s.lastElementChild){s.lastElementChild.scrollIntoView({block:'center'});}}}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = ChatScrollExpr, returnByValue = true });\n    await Task.Delay(200);\n    var ScreenShotCss = \"(function(){try{var s=document.createElement('style');s.textContent='html,body{margin:0 !important;padding:0 !important;padding-bottom:60vh !important}body>*:first-child{margin-top:0 !important;padding-top:0 !important}';document.head.appendChild(s);window.scrollTo(0,0);}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = ScreenShotCss, returnByValue = true });\n    await Task.Delay(200);\n    var MarketScrollExpr = \"(function(){try{if(location.pathname.indexOf('/Marketplace')>-1){var l=document.querySelector('.Listing,.MarketplaceCard,article.Card');if(l){l.scrollIntoView({block:'center'});}}}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = MarketScrollExpr, returnByValue = true });\n    await Task.Delay(200);\n    var DocsScrollExpr = \"(function(){try{if(location.pathname.indexOf('/Documents')>-1){var d=document.querySelector('.DocBadge.Done')||document.querySelector('.DocBadge,.DocCard,.UploadedDoc');if(d){d.scrollIntoView({block:'center'});}}}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = DocsScrollExpr, returnByValue = true });\n    await Task.Delay(200);";
        public const string Replace_01 = "    await Cdp.DismissInfobarAsync();\n    var ScreenShotCss = \"(function(){try{var s=document.createElement('style');s.textContent='html,body{margin:0 !important;padding:0 !important;padding-bottom:60vh !important}body>*:first-child{margin-top:0 !important;padding-top:0 !important}';document.head.appendChild(s);window.scrollTo(0,0);}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = ScreenShotCss, returnByValue = true });\n    await Task.Delay(200);\n    var MarketScrollExpr = \"(function(){try{if(location.pathname.indexOf('/Marketplace')>-1){var l=document.querySelector('.Listing,.MarketplaceCard,article.Card');if(l){l.scrollIntoView({block:'center'});}}}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = MarketScrollExpr, returnByValue = true });\n    await Task.Delay(200);\n    var DocsScrollExpr = \"(function(){try{if(location.pathname.indexOf('/Documents')>-1){var d=document.querySelector('.DocBadge.Done')||document.querySelector('.DocBadge,.DocCard,.UploadedDoc');if(d){d.scrollIntoView({block:'center'});}}}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = DocsScrollExpr, returnByValue = true });\n    await Task.Delay(200);\n    var ChatScrollExpr = \"(function(){try{if(location.pathname.indexOf('/Chat')>-1||location.pathname.indexOf('/Sell/Chat')>-1||location.pathname.indexOf('/Dispatcher')>-1||location.pathname.indexOf('/Applicant')>-1){var s=document.querySelector('.ChatStream');if(s){var bubbles=s.querySelectorAll('.ChatBubble');var last=bubbles.length>0?bubbles[bubbles.length-1]:s.lastElementChild;if(last){last.scrollIntoView({block:'center',inline:'nearest'});}}}}catch(e){}})()\";\n    await Cdp.SendAsync(\"Runtime.evaluate\", new { expression = ChatScrollExpr, returnByValue = true });\n    await Task.Delay(200);";

        public const string Find_02 = "___UNUSED_SLOT___";
        public const string Replace_02 = "";
    }
}
