return 0;

namespace Scripts
{
    internal static class PatchSourceScratchConfig
    {
        public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\scripts\generic\rebuild-walkthrough-v3.cs";
        public const string Find_01 = "        if (Pad == \"011\")";
        public const string Replace_01 = "        if (Pad == \"042\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dh-china')) return 'already'; var p = document.createElement('div'); p.className = 'in-dh-china'; p.style.cssText = 'background:#dcfce7;border:2px solid #16a34a;border-radius:12px;padding:18px 22px;margin:16px;font-family:Arial,sans-serif;color:#14532d'; p.innerHTML = '<div style=font-size:20px;font-weight:800>You have been hired!</div><div style=font-size:15px;font-weight:500;margin-top:8px;color:#166534>Welcome Wei Liu. Badges: china-export, ocean-carrier. Your first job is ready.</div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(p, a.nextSibling); else s.insertBefore(p, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dh-china\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_02 = "        if (Pad == \"011\")";
        public const string Replace_02 = "        if (Pad == \"043\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dj-china')) return 'already'; var c = document.createElement('div'); c.className = 'in-dj-china'; c.style.cssText = 'background:white;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin:16px;font-family:Arial,sans-serif'; c.innerHTML = '<div style=display:flex;justify-content:space-between;align-items:center><div><div style=font-size:18px;font-weight:700;color:#0f172a>Hefei to Wilmington NC</div><div style=font-size:14px;color:#64748b;margin-top:4px>2024 BYD Han EV - Ocean carrier export - Cargo $48,500</div><div style=font-size:13px;color:#94a3b8;margin-top:6px>Pickup tomorrow - ETA 14 days - Pay $2,200</div></div><button style=background:#16a34a;color:white;border:none;border-radius:8px;padding:10px 20px;font-weight:700;font-size:14px>Accept</button></div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(c, a.nextSibling); else s.insertBefore(c, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dj-china\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_03 = "        if (Pad == \"011\")";
        public const string Replace_03 = "        if (Pad == \"044\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dh-la')) return 'already'; var p = document.createElement('div'); p.className = 'in-dh-la'; p.style.cssText = 'background:#dcfce7;border:2px solid #16a34a;border-radius:12px;padding:18px 22px;margin:16px;font-family:Arial,sans-serif;color:#14532d'; p.innerHTML = '<div style=font-size:20px;font-weight:800>You have been hired!</div><div style=font-size:15px;font-weight:500;margin-top:8px;color:#166534>Welcome Marco Rivera. Badges: port-LA-drayage. Drayage runs from Port of LA are queued for you.</div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(p, a.nextSibling); else s.insertBefore(p, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dh-la\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_04 = "        if (Pad == \"011\")";
        public const string Replace_04 = "        if (Pad == \"045\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dj-la')) return 'already'; var c = document.createElement('div'); c.className = 'in-dj-la'; c.style.cssText = 'background:white;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin:16px;font-family:Arial,sans-serif'; c.innerHTML = '<div style=display:flex;justify-content:space-between;align-items:center><div><div style=font-size:18px;font-weight:700;color:#0f172a>Port of LA to Inland warehouse</div><div style=font-size:14px;color:#64748b;margin-top:4px>BYD Han EV container drayage - Wei Zhang shipment</div><div style=font-size:13px;color:#94a3b8;margin-top:6px>Pickup today - 4 hr run - Pay $480</div></div><button style=background:#16a34a;color:white;border:none;border-radius:8px;padding:10px 20px;font-weight:700;font-size:14px>Accept</button></div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(c, a.nextSibling); else s.insertBefore(c, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dj-la\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_05 = "        if (Pad == \"011\")";
        public const string Replace_05 = "        if (Pad == \"046\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dh-team')) return 'already'; var p = document.createElement('div'); p.className = 'in-dh-team'; p.style.cssText = 'background:#dcfce7;border:2px solid #16a34a;border-radius:12px;padding:18px 22px;margin:16px;font-family:Arial,sans-serif;color:#14532d'; p.innerHTML = '<div style=font-size:20px;font-weight:800>You have been hired!</div><div style=font-size:15px;font-weight:500;margin-top:8px;color:#166534>Welcome Diego Morales and Maria Santos. Badges: cross-country-team. Long-haul team runs are ready.</div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(p, a.nextSibling); else s.insertBefore(p, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dh-team\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_06 = "        if (Pad == \"011\")";
        public const string Replace_06 = "        if (Pad == \"047\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dj-team')) return 'already'; var c = document.createElement('div'); c.className = 'in-dj-team'; c.style.cssText = 'background:white;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin:16px;font-family:Arial,sans-serif'; c.innerHTML = '<div style=display:flex;justify-content:space-between;align-items:center><div><div style=font-size:18px;font-weight:700;color:#0f172a>Inland warehouse to Wilmington NC</div><div style=font-size:14px;color:#64748b;margin-top:4px>BYD Han EV cross-country team haul - 2,800 mi - 2 drivers</div><div style=font-size:13px;color:#94a3b8;margin-top:6px>Pickup in 3 days - 4 day run - Pay $5,600 split</div></div><button style=background:#16a34a;color:white;border:none;border-radius:8px;padding:10px 20px;font-weight:700;font-size:14px>Accept</button></div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(c, a.nextSibling); else s.insertBefore(c, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dj-team\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_07 = "        if (Pad == \"011\")";
        public const string Replace_07 = "        if (Pad == \"048\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dh-final')) return 'already'; var p = document.createElement('div'); p.className = 'in-dh-final'; p.style.cssText = 'background:#dcfce7;border:2px solid #16a34a;border-radius:12px;padding:18px 22px;margin:16px;font-family:Arial,sans-serif;color:#14532d'; p.innerHTML = '<div style=font-size:20px;font-weight:800>You have been hired!</div><div style=font-size:15px;font-weight:500;margin-top:8px;color:#166534>Welcome Sam Chen Jr. Badges: auto-handling-final. Final-mile drop in Wilmington NC is queued.</div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(p, a.nextSibling); else s.insertBefore(p, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dh-final\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_08 = "        if (Pad == \"011\")";
        public const string Replace_08 = "        if (Pad == \"049\")\n        {\n            var Fn = \"() => { var s = document.querySelector('.Stage') || document.body; if (s.querySelector('.in-dj-final')) return 'already'; var c = document.createElement('div'); c.className = 'in-dj-final'; c.style.cssText = 'background:white;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin:16px;font-family:Arial,sans-serif'; c.innerHTML = '<div style=display:flex;justify-content:space-between;align-items:center><div><div style=font-size:18px;font-weight:700;color:#0f172a>Wilmington warehouse to buyer driveway</div><div style=font-size:14px;color:#64748b;margin-top:4px>BYD Han EV final delivery - Wei Zhang shipment</div><div style=font-size:13px;color:#94a3b8;margin-top:6px>Pickup tomorrow - 1 hr run - Pay $180</div></div><button style=background:#16a34a;color:white;border:none;border-radius:8px;padding:10px 20px;font-weight:700;font-size:14px>Accept</button></div>'; var a = s.querySelector('h1,h2,h3') || s.firstChild; if (a && a.parentNode) a.parentNode.insertBefore(c, a.nextSibling); else s.insertBefore(c, s.firstChild); return 'injected'; }\";\n            await Cdp(\"dj-final\", Eval(Fn));\n            await Task.Delay(1000);\n        }\n        if (Pad == \"011\")";
        public const string Find_09 = "        if (Pad == \"011\")";
        public const string Replace_09 = "        if (Pad == \"011\" || Pad == \"052\")";
    }
}
