namespace WolfsTruckingCo.Scripts.Specific;

public static class PatchSourceScratchConfigVChatUploadFix
{
    public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\src\SharedUI\Components\ChatBox.razor.cs";
    public const string Find_01 = "    private const string DefaultAttachTitle = \"Attach file\";\n\n    private const long MaxAttachmentBytes = 10 * 1024 * 1024;\n\n    private const int MaxAttachmentCount = 8;\n\n    private const string AttachedNotePrefix = \"📎 attached: \";\n\n    private const string JoinSeparator = \", \";";
    public const string Replace_01 = "    private const string DefaultAttachTitle = \"Attach file\";\n\n    private const long MaxAttachmentBytes = 10 * 1024 * 1024;\n\n    private const int MaxAttachmentCount = 8;\n\n    private const string AttachedNotePrefix = \"📎 attached: \";\n\n    private const string JoinSeparator = \", \";\n\n    private const string AssistantFallback = \"(agent offline — your message was logged)\";\n\n    private const string ChatAttachUrl = \"https://wolfstruckingco.nbth.workers.dev/api/chat-attach\";\n\n    private const string FilenameQueryKey = \"?filename=\";\n\n    private const string DefaultContentType = \"application/octet-stream\";\n\n    private const string UploadFailedSuffix = \" (upload failed)\";\n\n    private const string UploadErrorSuffix = \" (upload error)\";";
    public const string Find_02 = "    private const string AssistantFallback = \"(agent offline — your message was logged)\";\n\n    private async Task SendAsync()";
    public const string Replace_02 = "    private async Task SendAsync()";
    public const string Find_03 = "    private const string ChatAttachUrl = \"https://wolfstruckingco.nbth.workers.dev/api/chat-attach\";\n\n    private async Task OnFilesAttachedAsync(InputFileChangeEventArgs E)\n    {\n        var Names = new List<string>();\n        foreach (var F in E.GetMultipleFiles(maximumFileCount: MaxAttachmentCount))\n        {\n            if (F.Size > MaxAttachmentBytes) { continue; }\n            try\n            {\n                using var Stream = F.OpenReadStream(MaxAttachmentBytes);\n                using var Content = new StreamContent(Stream);\n                Content.Headers.ContentType = new MediaTypeHeaderValue(string.IsNullOrEmpty(F.ContentType) ? \"application/octet-stream\" : F.ContentType);\n                var Url = ChatAttachUrl + \"?filename=\" + Uri.EscapeDataString(F.Name);\n                using var Response = await Http.PostAsync(new Uri(Url), Content);\n                Names.Add(F.Name + (Response.IsSuccessStatusCode ? string.Empty : \" (upload failed)\"));\n            }\n#pragma warning disable CA1031\n            catch\n#pragma warning restore CA1031\n            {\n                Names.Add(F.Name + \" (upload error)\");\n            }\n        }\n\n        if (Names.Count > 0)\n        {\n            Live.Add(new ChatMessage(RoleUser, AttachedNotePrefix + string.Join(JoinSeparator, Names)));\n        }\n    }";
    public const string Replace_03 = "    private async Task OnFilesAttachedAsync(InputFileChangeEventArgs E)\n    {\n        var Names = new List<string>();\n        foreach (var F in E.GetMultipleFiles(maximumFileCount: MaxAttachmentCount))\n        {\n            if (F.Size > MaxAttachmentBytes) { continue; }\n            try\n            {\n                await using var Stream = F.OpenReadStream(MaxAttachmentBytes);\n                using var Content = new StreamContent(Stream);\n                Content.Headers.ContentType = new MediaTypeHeaderValue(string.IsNullOrEmpty(F.ContentType) ? DefaultContentType : F.ContentType);\n                var Url = ChatAttachUrl + FilenameQueryKey + Uri.EscapeDataString(F.Name);\n                using var Response = await Http.PostAsync(new Uri(Url), Content);\n                Names.Add(F.Name + (Response.IsSuccessStatusCode ? string.Empty : UploadFailedSuffix));\n            }\n#pragma warning disable CA1031\n            catch\n#pragma warning restore CA1031\n            {\n                Names.Add(F.Name + UploadErrorSuffix);\n            }\n        }\n\n        if (Names.Count > 0)\n        {\n            Live.Add(new ChatMessage(RoleUser, AttachedNotePrefix + string.Join(JoinSeparator, Names)));\n        }\n    }";
}
