namespace WolfsTruckingCo.Scripts.Specific;

public static class PatchSourceScratchConfigVAttachHandler3
{
    public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\src\SharedUI\Components\ChatBox.razor.cs";
    public const string Find_01 = "    private const long MaxAttachmentBytes = 10 * 1024 * 1024;\n\n    private const int MaxAttachmentCount = 8;\n\n    private const string AttachedNotePrefix = \"📎 attached: \";\n\n    private const string JoinSeparator = \", \";\n\n    private async Task OnKeyAsync(KeyboardEventArgs E)\n    {\n        if (string.Equals(E.Key, EnterKey, StringComparison.Ordinal) && !E.ShiftKey) { await SendAsync(); }\n    }\n\n    private Task OnFilesAttachedAsync(InputFileChangeEventArgs E)\n    {\n        var Names = new List<string>();\n        foreach (var F in E.GetMultipleFiles(maximumFileCount: MaxAttachmentCount))\n        {\n            if (F.Size > MaxAttachmentBytes) { continue; }\n            Names.Add(F.Name);\n        }\n        if (Names.Count > 0)\n        {\n            Live.Add(new ChatMessage(RoleUser, AttachedNotePrefix + string.Join(JoinSeparator, Names)));\n        }\n        return Task.CompletedTask;\n    }\n}";
    public const string Replace_01 = "    private async Task OnKeyAsync(KeyboardEventArgs E)\n    {\n        if (string.Equals(E.Key, EnterKey, StringComparison.Ordinal) && !E.ShiftKey) { await SendAsync(); }\n    }\n\n    private Task OnFilesAttachedAsync(InputFileChangeEventArgs E)\n    {\n        var Names = new List<string>();\n        foreach (var F in E.GetMultipleFiles(maximumFileCount: MaxAttachmentCount))\n        {\n            if (F.Size > MaxAttachmentBytes) { continue; }\n            Names.Add(F.Name);\n        }\n\n        if (Names.Count > 0)\n        {\n            Live.Add(new ChatMessage(RoleUser, AttachedNotePrefix + string.Join(JoinSeparator, Names)));\n        }\n\n        return Task.CompletedTask;\n    }\n}";
    public const string Find_02 = "    private const string DefaultAttachTitle = \"Attach file\";";
    public const string Replace_02 = "    private const string DefaultAttachTitle = \"Attach file\";\n\n    private const long MaxAttachmentBytes = 10 * 1024 * 1024;\n\n    private const int MaxAttachmentCount = 8;\n\n    private const string AttachedNotePrefix = \"📎 attached: \";\n\n    private const string JoinSeparator = \", \";";
}
