return 0;

namespace Scripts
{
    internal static class PatchSourceV4NewtabReadyWaitScratchConfigV1
    {
        public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\scripts\generic\rebuild-walkthrough-v4.cs";
        public const string Find_01 = "async Task ReplaceTab(string Url) { await NewPageAt(Url); await Task.Delay(2500); var Listing = await PostServeAsync(\"list_pages\"); var Cleaned = Url.Contains('?', StringComparison.Ordinal) ? Url[..Url.IndexOf('?', StringComparison.Ordinal)] : Url; foreach (var Line in Listing.Split('\\n')) { var T = Line.Trim(); if (!T.Contains(Cleaned, StringComparison.OrdinalIgnoreCase)) continue; var Colon = T.IndexOf(':'); if (Colon < 1) continue; var Idx = T.Substring(0, Colon).Trim(); if (Idx.All(char.IsDigit)) { CachedWolfsPageIdx = Idx; break; } } }";
        public const string Replace_01 = "async Task ReplaceTab(string Url) { await NewPageAt(Url); await Task.Delay(2500); while (true) { var NtList = await PostServeAsync(\"list_pages\"); var NtIdx = \"\"; foreach (var Line in NtList.Split('\\n')) { var T = Line.Trim(); if (!T.Contains(\"chrome://newtab/\", StringComparison.Ordinal)) continue; var Colon = T.IndexOf(':'); if (Colon < 1) continue; var Idx = T.Substring(0, Colon).Trim(); if (Idx.All(char.IsDigit)) { NtIdx = Idx; break; } } if (string.IsNullOrEmpty(NtIdx)) break; await Cdp(\"close-nt\", \"public const string Command = \\u0022close_page\\u0022;\\n        public const string PageId = \\u0022\" + NtIdx + \"\\u0022;\"); await Task.Delay(500); } var Listing = await PostServeAsync(\"list_pages\"); var Cleaned = Url.Contains('?', StringComparison.Ordinal) ? Url[..Url.IndexOf('?', StringComparison.Ordinal)] : Url; foreach (var Line in Listing.Split('\\n')) { var T = Line.Trim(); if (!T.Contains(Cleaned, StringComparison.OrdinalIgnoreCase)) continue; var Colon = T.IndexOf(':'); if (Colon < 1) continue; var Idx = T.Substring(0, Colon).Trim(); if (Idx.All(char.IsDigit)) { CachedWolfsPageIdx = Idx; break; } } if (!string.IsNullOrEmpty(CachedWolfsPageIdx)) { for (int RIter = 0; RIter < 30; RIter++) { var ReadyEval = await CdpRead(\"ready-chk\", \"public const string Command = \\u0022evaluate_script\\u0022;\\n        public const string PageId = \\u0022\" + CachedWolfsPageIdx + \"\\u0022;\\n        public const string Function = \\u0022() => document.readyState.charCodeAt(0) === 99 && typeof window.Blazor !== typeof undefined\\u0022;\"); if (ReadyEval.Contains(\"true\", StringComparison.Ordinal)) break; await Task.Delay(1000); } } }";
    }
}
