namespace WolfsTruckingCo.Scripts.Specific;

public static class PatchSourceScratchConfigVChatUpload
{
    public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\src\SharedUI\Components\ChatBox.razor.cs";
    public const string Find_01 = "using System;\nusing System.Collections.Generic;\nusing System.Threading.Tasks;\nusing Microsoft.AspNetCore.Components;\nusing Microsoft.AspNetCore.Components.Forms;\nusing Microsoft.AspNetCore.Components.Web;\nusing SharedUI.Services;";
    public const string Replace_01 = "using System;\nusing System.Collections.Generic;\nusing System.Net.Http;\nusing System.Net.Http.Headers;\nusing System.Threading.Tasks;\nusing Microsoft.AspNetCore.Components;\nusing Microsoft.AspNetCore.Components.Forms;\nusing Microsoft.AspNetCore.Components.Web;\nusing SharedUI.Services;";
    public const string Find_02 = "    [Inject]\n    private WolfsInteropService Wolfs { get; set; } = null!;";
    public const string Replace_02 = "    [Inject]\n    private WolfsInteropService Wolfs { get; set; } = null!;\n\n    [Inject]\n    private HttpClient Http { get; set; } = null!;";
    public const string Find_03 = "    private async Task SendAsync()\n    {\n        var Msg = (Draft ?? string.Empty).Trim();\n        if (string.IsNullOrEmpty(Msg) || Sending) { return; }\n        Sending = true;\n        Live.Add(new ChatMessage(RoleUser, Msg));\n        Draft = string.Empty;\n        try\n        {\n            var Reply = await Wolfs.ChatReplyAsync(SystemPrompt, Live, MaxTokens);\n            Live.Add(new ChatMessage(RoleAssistant, Reply));\n        }\n        finally { Sending = false; }\n    }";
    public const string Replace_03 = "    private const string AssistantFallback = \"(agent offline — your message was logged)\";\n\n    private async Task SendAsync()\n    {\n        var Msg = (Draft ?? string.Empty).Trim();\n        if (string.IsNullOrEmpty(Msg) || Sending) { return; }\n        Sending = true;\n        Live.Add(new ChatMessage(RoleUser, Msg));\n        Draft = string.Empty;\n        try\n        {\n            var Reply = await Wolfs.ChatReplyAsync(SystemPrompt, Live, MaxTokens);\n            Live.Add(new ChatMessage(RoleAssistant, string.IsNullOrEmpty(Reply) ? AssistantFallback : Reply));\n        }\n#pragma warning disable CA1031\n        catch\n#pragma warning restore CA1031\n        {\n            Live.Add(new ChatMessage(RoleAssistant, AssistantFallback));\n        }\n        finally { Sending = false; }\n    }";
    public const string Find_04 = "    private Task OnFilesAttachedAsync(InputFileChangeEventArgs E)\n    {\n        var Names = new List<string>();\n        foreach (var F in E.GetMultipleFiles(maximumFileCount: MaxAttachmentCount))\n        {\n            if (F.Size > MaxAttachmentBytes) { continue; }\n            Names.Add(F.Name);\n        }\n\n        if (Names.Count > 0)\n        {\n            Live.Add(new ChatMessage(RoleUser, AttachedNotePrefix + string.Join(JoinSeparator, Names)));\n        }\n\n        return Task.CompletedTask;\n    }";
    public const string Replace_04 = "    private const string ChatAttachUrl = \"https://wolfstruckingco.nbth.workers.dev/api/chat-attach\";\n\n    private async Task OnFilesAttachedAsync(InputFileChangeEventArgs E)\n    {\n        var Names = new List<string>();\n        foreach (var F in E.GetMultipleFiles(maximumFileCount: MaxAttachmentCount))\n        {\n            if (F.Size > MaxAttachmentBytes) { continue; }\n            try\n            {\n                using var Stream = F.OpenReadStream(MaxAttachmentBytes);\n                using var Content = new StreamContent(Stream);\n                Content.Headers.ContentType = new MediaTypeHeaderValue(string.IsNullOrEmpty(F.ContentType) ? \"application/octet-stream\" : F.ContentType);\n                var Url = ChatAttachUrl + \"?filename=\" + Uri.EscapeDataString(F.Name);\n                using var Response = await Http.PostAsync(new Uri(Url), Content);\n                Names.Add(F.Name + (Response.IsSuccessStatusCode ? string.Empty : \" (upload failed)\"));\n            }\n#pragma warning disable CA1031\n            catch\n#pragma warning restore CA1031\n            {\n                Names.Add(F.Name + \" (upload error)\");\n            }\n        }\n\n        if (Names.Count > 0)\n        {\n            Live.Add(new ChatMessage(RoleUser, AttachedNotePrefix + string.Join(JoinSeparator, Names)));\n        }\n    }";
}
