return 0;

namespace Scripts
{
    internal static class WriteFileScratchConfig
    {
        public const string TargetFile = @"C:\repo\public\wolfstruckingco.com\main\scripts\generic\regen-worker-cs.cs";
        public const string Content = "#:property TargetFramework=net11.0\n\nusing System.Text;\n\nif (args.Length < 1)\n{\n    return 1;\n}\n\nvar Specs = await File.ReadAllLinesAsync(args[0]);\n\nstring Get(string Name)\n{\n    foreach (var Line in Specs)\n    {\n        var Pat = \"const string \" + Name + \" = \";\n        var At = Line.IndexOf(Pat, StringComparison.Ordinal);\n        if (At < 0)\n        {\n            continue;\n        }\n\n        var Tail = Line[(At + Pat.Length)..];\n        if (Tail.Length > 0 && Tail[0] == '@')\n        {\n            Tail = Tail[1..];\n        }\n\n        if (Tail.Length == 0 || Tail[0] != '\\u0022')\n        {\n            continue;\n        }\n\n        var End = Tail.LastIndexOf(\"\\u0022;\", StringComparison.Ordinal);\n        if (End < 1)\n        {\n            continue;\n        }\n\n        return Tail[1..End];\n    }\n\n    return string.Empty;\n}\n\nvar JsPath = Get(\"JsPath\");\nvar CsPath = Get(\"CsPath\");\n\nif (!File.Exists(JsPath))\n{\n    return 2;\n}\n\nvar Bytes = await File.ReadAllBytesAsync(JsPath);\nvar B64 = Convert.ToBase64String(Bytes);\n\nvar Sb = new StringBuilder();\nSb.AppendLine(\"#:property TargetFramework=net11.0\");\nSb.AppendLine(\"#:property RunAnalyzersDuringBuild=false\");\nSb.AppendLine(\"#:property TreatWarningsAsErrors=false\");\nSb.AppendLine(\"#:property EnforceCodeStyleInBuild=false\");\nSb.AppendLine();\nSb.Append(\"const string Path = \\\"\");\nSb.Append(JsPath.Replace(\"\\\\\", \"\\\\\\\\\", StringComparison.Ordinal));\nSb.AppendLine(\"\\\";\");\nSb.AppendLine(\"var B64 = $\\\"{string.Join(string.Empty, JsBody())}\\\";\");\nSb.AppendLine(\"var Bytes = Convert.FromBase64String(B64);\");\nSb.AppendLine(\"File.WriteAllBytes(Path, Bytes);\");\nSb.AppendLine(\"return 0;\");\nSb.AppendLine();\nSb.AppendLine(\"static string[] JsBody() => new[]\");\nSb.AppendLine(\"{\");\n\nvar ChunkSize = 100;\nfor (var I = 0; I < B64.Length; I += ChunkSize)\n{\n    var Len = Math.Min(ChunkSize, B64.Length - I);\n    Sb.Append(\"    \\\"\");\n    Sb.Append(B64.AsSpan(I, Len));\n    Sb.AppendLine(\"\\\",\");\n}\n\nSb.AppendLine(\"};\");\n\nawait File.WriteAllTextAsync(CsPath, Sb.ToString());\nreturn 0;\n";
        public const string Mode = "overwrite";
    }
}
