return 0;

namespace Scripts
{
    internal static class WriteFileScratchConfigV3
    {
        public const string TargetFile = "main/scripts/generic/SharedScripts.cs";
        public const string Mode = "overwrite";
        public const string Content = "namespace Scripts;\n\nusing System.Text.RegularExpressions;\n\ninternal static partial class SharedPatterns\n{\n    [GeneratedRegex(\"\"\"const\\s+string\\s+(?<name>\\w+)\\s*=\\s*@?\"(?<value>(?:[^\"\\\\]|\\\\.)*)\"\\s*;\"\"\", RegexOptions.ExplicitCapture)]\n    internal static partial Regex ConstString();\n\n    [GeneratedRegex(@\"const\\s+int\\s+(?<name>\\w+)\\s*=\\s*(?<value>-?\\d+)\\s*;\", RegexOptions.ExplicitCapture)]\n    internal static partial Regex ConstInt();\n}\n\ninternal static class ScratchConfig\n{\n    public static async Task<Dictionary<string, string>> LoadStringsAsync(string ConfigPath)\n    {\n        var Body = await File.ReadAllTextAsync(ConfigPath);\n        return SharedPatterns.ConstString().Matches(Body)\n            .ToDictionary(M => M.Groups[\"name\"].Value, M => M.Groups[\"value\"].Value, StringComparer.Ordinal);\n    }\n\n    public static async Task<Dictionary<string, int>> LoadIntsAsync(string ConfigPath)\n    {\n        var Body = await File.ReadAllTextAsync(ConfigPath);\n        return SharedPatterns.ConstInt().Matches(Body)\n            .ToDictionary(M => M.Groups[\"name\"].Value, M => int.Parse(M.Groups[\"value\"].Value, System.Globalization.CultureInfo.InvariantCulture), StringComparer.Ordinal);\n    }\n\n    public static Dictionary<string, string> ParseStrings(string Body)\n    {\n        return SharedPatterns.ConstString().Matches(Body)\n            .ToDictionary(M => M.Groups[\"name\"].Value, M => M.Groups[\"value\"].Value, StringComparer.Ordinal);\n    }\n\n    public static Dictionary<string, int> ParseInts(string Body)\n    {\n        return SharedPatterns.ConstInt().Matches(Body)\n            .ToDictionary(M => M.Groups[\"name\"].Value, M => int.Parse(M.Groups[\"value\"].Value, System.Globalization.CultureInfo.InvariantCulture), StringComparer.Ordinal);\n    }\n}\n\ninternal static class Errors\n{\n    public static async Task<int> FailAsync(string Message, int Code)\n    {\n        await Console.Error.WriteLineAsync(Message);\n        return Code;\n    }\n}\n";
    }
}
